const data={
    products:[
    {
      _id:'1',
      image:'/resimler/resim1.jpg',
      image2:'/resimler/versace1.jpg',
      image3:'/resimler/versace2.jpg',
      image4:'/resimler/versace3.jpg',
      brand:'VERSACE JEANS',
      name:'Erkek Giyim',
      yorum:37,
      price:1499.99,
      description:'Tişörtler,Yuvarlak Yaka,Kısa Kollu',
      icerikbir:'Genellikle 1 iş günü içerisinde temin edilir.',
      icerikiki:'%100 Pamuk',
      color:'Siyah-Sarı',
      beden:['XS','S','M','L','XL'],
      stock:15,
    },
    
    {
      _id:'2',
      image:'/resimler/resim3.jpg',
      image2:'/resimler/versace7.jpg', 
      image3:'/resimler/versace8.jpg',
      image4:'/resimler/versace9.jpg',   
      brand:'VERSACE JEANS',
      name:'Erkek Giyim',  
      yorum:63,
      price:1999.99,
      description:'Svetşörtler, Yuvarlak yaka hattı, Uzun kollar, Ribana kenar',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%100 Pamuk',
      color:'Siyah',
      beden:['XS','S','M','L','XL'],
      stock:9,
    },
    
    {
      _id:'3',
      image:'/resimler/resim4.jpg',
      image2:'/resimler/versace10.jpg', 
      image3:'/resimler/versace11.jpg',
      image4:'/resimler/versace12.jpg',    
      brand:'VERSACE JEANS',
      name:'Erkek Giyim',  
      yorum:82,
      price:1899.99,
      description:'Gömlekler, Rahat kesim, Baroque Details, Düğmeli pat',
      icerikbir:'Genellikle 3 iş günü içerisinde temin edilir.',
      icerikiki:'Viskoz',
      color:'Siyah',
      beden:['XS','S','M','L','XL'],
      stock:7,
    },
    {
      _id:'4',
      image:'/resimler/resim2.jpg',
      image2:'/resimler/versace4.jpg',
      image3:'/resimler/versace5.jpg',
      image4:'/resimler/versace6.jpg',
      brand:'VERSACE JEANS',
      name:'Erkek Giyim',
      yorum:39,
      price:1749.99,
      description:'Pantolonlar, Yanda eğimli cepler, Nervürlü kenar baskısı ',
      icerikbir:'Genellikle 1 iş günü içerisinde temin edilir.',
      icerikiki:'%100 Pamuk',
      color:'Siyah-Sarı',
      beden:['XS','S','M','L','XL'],
      stock:12,
    },
    {
      _id:'5',
      image:'/resimler/resim5.jpg',
      image2:'/resimler/hugo1.jpg', 
      image3:'/resimler/hugo2.jpg',
      image4:'/resimler/hugo3.jpg',    
      brand:'HUGO BOSS',
      name:'Erkek Giyim',  
      yorum:17,
      price:699.99,
      description:'Polo Tişörtler, Kısa kollu, Göğüs üzerinde logo, Üç düğme kapatma',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%100 Pamuk',
      color:'Denizci Mavisi',
      beden:['XS','S','M','L','XL'],
      stock:15,
    },
    {
      _id:'6',
      image:'/resimler/resim6.jpg',
      image2:'/resimler/hugo4.jpg', 
      image3:'/resimler/hugo5.jpg',
      image4:'/resimler/hugo6.jpg',    
      brand:'HUGO BOSS',
      name:'Erkek Giyim',  
      yorum:11,
      price:949.99,
      description:'Kotlar, Fermuarlı-Düğmeli pat, Beş cepli stil, Ekstra dar kesim',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%79 Pamuk, %20 Diğer materyaller, %1 Elastan',
      color:'Mavi',
      beden:['XS','S','M','L','XL'],
      stock:8,
    },
    {
      _id:'7',
      image:'/resimler/resim7.jpg',
      image2:'/resimler/paulshark1.jpg', 
      image3:'/resimler/paulshark2.jpg',
      image4:'/resimler/paulshark3.jpg',    
      brand:'PAUL & SHARK',
      name:'Erkek Giyim',  
      yorum:27,
      price:974.99,
      description:'Svetşörtler, Yuvarlak yaka hattı, Önde logo, Ribana kenar',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%75 Pamuk, %20 Polyester, %5 Elastan',
      color:'Mavi',
      beden:['XS','S','M','L','XL'],
      stock:12,
    },
    {
      _id:'8',
      image:'/resimler/resim8.jpg',
      image2:'/resimler/paulshark4.jpg', 
      image3:'/resimler/paulshark5.jpg',
      image4:'/resimler/paulshark6.jpg',    
      brand:'PAUL & SHARK',
      name:'Erkek Giyim',  
      yorum:87,
      price:1099.99,
      description:'Şortlar, Lastikli bel, İki ön cep, Tek arka cep, Yüzme şortu',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%100 Polyester',
      color:'Denizci Mavisi',
      beden:['XS','S','M','L','XL'],
      stock:9,
    },
    {
      _id:'9',
      image:'/resimler/resim9.jpg',
      image2:'/resimler/moncler1.jpg', 
      image3:'/resimler/moncler2.jpg',
      image4:'/resimler/moncler3.jpg',    
      brand:'MONCLER',
      name:'Erkek Giyim',  
      yorum:47,
      price:2999.99,
      description:'Şortlar, Lastikli bel, İki ön cep, Tek arka cep, Yüzme şortu',
      icerikbir:'Genellikle 1 iş günü içerisinde temin edilir.',
      icerikiki:'%100 Pamuk',
      color:'Siyah',
      beden:['XS','S','M','L','XL'],
      stock:26,
    },
    {
      _id:'10',
      image:'/resimler/resim10.jpg',
      image2:'/resimler/moncler4.jpg', 
      image3:'/resimler/moncler5.jpg',
      image4:'/resimler/moncler6.jpg',    
      brand:'MONCLER',
      name:'Erkek Giyim',  
      yorum:17,
      price:11999.99,
      description:'Dolgulu Montlar, Başlıkta çıkarılabilir kürk, Önde fermuarlı cepler, Çıtçıt düğmeli manşetler • Fermuarlı iç cep, Fermuar kapatma',
      icerikbir:'Genellikle 1 iş günü içerisinde temin edilir.',
      icerikiki:'%100 Poliamid',
      color:'Siyah',
      beden:['XS','S','M','L','XL'],
      stock:11,
    },
    {
      _id:'11',
      image:'/resimler/resim11.jpg',
      image2:'/resimler/armani1.jpg', 
      image3:'/resimler/armani2.jpg',
      image4:'/resimler/armani3.jpg',    
      brand:'EMPORIO ARMANI',
      name:'Erkek Giyim',  
      yorum:34,
      price:1299.99,
      description:'Svetşörtler, Yuvarlak yaka',
      icerikbir:'Genellikle 1 iş günü içerisinde temin edilir.',
      icerikiki:'%36 Pamuk, %64 Polyester',
      color:'Beyaz-Yeşil',
      beden:['XS','S','M','L','XL'],
      stock:16,
    },
    {
      _id:'12',
      image:'/resimler/resim12.jpg',
      image2:'/resimler/armani4.jpg', 
      image3:'/resimler/armani5.jpg',
      image4:'/resimler/armani6.jpg',    
      brand:'EMPORİO ARMANİ',
      name:'Erkek Giyim',  
      yorum:314,
      price:674.99,
      description:'Tişörtler, Bisiklet yaka, Kısa kollu',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%100 Pamuk',
      color:'Okyanus Mavisi',
      beden:['XS','S','M','L','XL'],
      stock:24,
    },
    {
      _id:'13',
      image:'/resimler/resim13.jpg',
      image2:'/resimler/armani7.jpg', 
      image3:'/resimler/armani8.jpg',
      image4:'/resimler/armani9.jpg',    
      brand:'EMPORİO ARMANİ',
      name:'Erkek Giyim',  
      yorum:214,
      price:899.99,
      description:'Tişörtler, Bisiklet yaka, Kısa kollu',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%100 Pamuk',
      color:'Kırmızı',
      beden:['XS','S','M','L','XL'],
      stock:17,
    },
    {
      _id:'14',
      image:'/resimler/resim14.jpg',
      image2:'/resimler/armani10.jpg', 
      image3:'/resimler/armani11.jpg',
      image4:'/resimler/armani12.jpg',    
      brand:'EMPORİO ARMANİ',
      name:'Erkek Giyim',  
      yorum:325,
      price:2499.99,
      description:'Pantolonlar, Fermuar ve düğmeli pat, İki ön cep, İki arka cep, Çizgili desen',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%46 Pamuk, %38 Polyester, %16 Keten',
      color:'Beyaz',
      beden:['XS','S','M','L','XL'],
      stock:47,
    },
    {
      _id:'15',
      image:'/resimler/resim15.jpg',
      image2:'/resimler/armani13.jpg', 
      image3:'/resimler/armani14.jpg',
      image4:'/resimler/armani15.jpg',    
      brand:'EMPORİO ARMANİ',
      name:'Erkek Giyim',  
      yorum:475,
      price:599.99,
      description:'Tişörtler, Bisiklet yaka, Kısa kollu',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%100 Pamuk',
      color:'Safran',
      beden:['XS','S','M','L','XL'],
      stock:98,
    },
    {
      _id:'16',
      image:'/resimler/resim16.jpg',
      image2:'/resimler/armani16.jpg', 
      image3:'/resimler/armani17.jpg',
      image4:'/resimler/armani18.jpg',    
      brand:'EMPORİO ARMANİ',
      name:'Kadın Giyim',  
      yorum:415,
      price:1199.99,
      description:'Etekler, Fermuarlı-Düğmeli pat, Beş cepli stil',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%100 Pamuk',
      color:'Siyah',
      beden:['XS','S','M','L','XL'],
      stock:52,
    },
    {
      _id:'17',
      image:'/resimler/resim17.jpg',
      image2:'/resimler/armani19.jpg', 
      image3:'/resimler/armani20.jpg',
      image4:'/resimler/armani21.jpg',    
      brand:'EMPORİO ARMANİ',
      name:'Kadın Giyim',  
      yorum:145,
      price:3399.99,
      description:'Elbiseler,Arkada fermuar',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%77 Viskoz, %17 Poliamid, %6 Elastan',
      color:'Siyah',
      beden:['XS','S','M','L','XL'],
      stock:70,
    },
    {
      _id:'18',
      image:'/resimler/resim18.jpg',
      image2:'/resimler/armani22.jpg', 
      image3:'/resimler/armani23.jpg',
      image4:'/resimler/armani24.jpg',    
      brand:'EMPORİO ARMANİ',
      name:'Kadın Giyim',  
      yorum:255,
      price:2749.99,
      description:'Pantolonlar, Kopça ve Fermuar Kapatma',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%50 Viskoz, %47 Asetat, %3 Elastan',
      color:'Kırmızı',
      beden:['XS','S','M','L','XL'],
      stock:18,
    },
    {
      _id:'19',
      image:'/resimler/resim19.jpg',
      image2:'/resimler/armani25.jpg', 
      image3:'/resimler/armani26.jpg',
      image4:'/resimler/armani27.jpg',    
      brand:'EMPORİO ARMANİ',
      name:'Kadın Giyim',  
      yorum:100,
      price:1249.99,
      description:'Bluzlar, Yuvarlak yaka, Kısa kol',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%60 Liyosel, %40 Poliamid',
      color:'Su Mavisi',
      beden:['XS','S','M','L','XL'],
      stock:75,
    },
    {
      _id:'20',
      image:'/resimler/resim20.jpg',
      image2:'/resimler/armani28.jpg', 
      image3:'/resimler/armani29.jpg',
      image4:'/resimler/armani30.jpg',    
      brand:'EMPORİO ARMANİ',
      name:'Kadın Giyim',  
      yorum:119,
      price:1199.99,
      description:'Svetşörtler,Yuvarlak yaka',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%88 Pamuk, %12 Polyester',
      color:'Beyaz',
      beden:['XS','S','M','L','XL'],
      stock:115,
    },
    {
      _id:'21',
      image:'/resimler/resim21.jpg',
      image2:'/resimler/versace13.jpg', 
      image3:'/resimler/versace14.jpg',
      image4:'/resimler/versace15.jpg',    
      brand:'VERSACE JEANS',
      name:'Kadın Giyim',  
      yorum:205,
      price:1999.99,
      description:'Kazaklar, Yuvarlak yaka, Uzun kollar, Ribana kenar',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%77 Viskoz, %23 Poliamid',
      color:'Siyah-Pembe-Sarı',
      beden:['XS','S','M','L','XL'],
      stock:105,
    },
    {
      _id:'22',
      image:'/resimler/resim22.jpg',
      image2:'/resimler/versace16.jpg', 
      image3:'/resimler/versace17.jpg',
      image4:'/resimler/versace18.jpg',    
      brand:'VERSACE JEANS',
      name:'Kadın Giyim',  
      yorum:145,
      price:1399.99,
      description:'Bluzlar,Kısa kollu, V yaka, Badi',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%92 Pamuk, %8 Elastan',
      color:'Sarı',
      beden:['XS','S','M','L','XL'],
      stock:41,
    },
    {
      _id:'23',
      image:'/resimler/resim23.jpg',
      image2:'/resimler/versace19.jpg', 
      image3:'/resimler/versace20.jpg',
      image4:'/resimler/versace21.jpg',    
      brand:'VERSACE JEANS',
      name:'Kadın Giyim',  
      yorum:'15',
      price:1199.99,
      description:'Tişörtler',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%100 Pamuk',
      color:'Lavanta',
      beden:['XS','S','M','L','XL'],
      stock:75,
    },
    {
      _id:'24',
      image:'/resimler/resim24.jpg',
      image2:'/resimler/versace22.jpg', 
      image3:'/resimler/versace23.jpg',
      image4:'/resimler/versace24.jpg',    
      brand:'VERSACE JEANS',
      name:'Kadın Giyim',  
      yorum:15,
      price:2399.99,
      description:'Elbiseler, Spagetti askılar',
      icerikbir:'Genellikle 3 iş günü içerisinde temin edilir.',
      icerikiki:'%100 Polyester',
      color:'Nane Yeşili',
      beden:['XS','S','M','L','XL'],
      stock:10,
    },
    {
      _id:'25',
      image:'/resimler/resim25.jpg',
      image2:'/resimler/kors1.jpg', 
      image3:'/resimler/kors2.jpg',
      image4:'/resimler/kors3.jpg',    
      brand:'MİCHAEL KORS',
      name:'Kadın Giyim',  
      yorum:157,
      price:749.99,
      description:'Tişörtler, Yuvarlak yaka, Kısa kol',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%100 Organik Pamuk',
      color:'Beyaz',
      beden:['XS','S','M','L','XL'],
      stock:70,
    },
    {
      _id:'26',
      image:'/resimler/resim26.jpg',
      image2:'/resimler/kors4.jpg', 
      image3:'/resimler/kors5.jpg',
      image4:'/resimler/kors6.jpg',    
      brand:'MİCHAEL KORS',
      name:'Kadın Giyim',  
      yorum:199,
      price:1969.99,
      description:'Elbiseler, Arkada fermuarlı kapatma, Kolsuz, Belden kemerle bağlı,nYan cepler',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%96 Pamuk, %4 Elastan',
      color:'Kırmızı',
      beden:['XS','S','M','L','XL'],
      stock:21,
    },
    {
      _id:'27',
      image:'/resimler/resim27.jpg',
      image2:'/resimler/moncler7.jpg', 
      image3:'/resimler/moncler8.jpg',
      image4:'/resimler/moncler9.jpg',    
      brand:'MONCLER',
      name:'Kadın Giyim',  
      yorum:266,
      price:1974.99,
      description:'Kazaklar, Üste oturan kesim, Balıkçı yaka',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%71 Viskoz, %28 Poliamid, %1 Elastan',
      color:'Siyah',
      beden:['XS','S','M','L','XL'],
      stock:7,
    },
    {
      _id:'28',
      image:'/resimler/resim28.jpg',
      image2:'/resimler/moncler10.jpg', 
      image3:'/resimler/moncler11.jpg',
      image4:'/resimler/moncler12.jpg',    
      brand:'MONCLER',
      name:'Kadın Giyim',  
      yorum:76,
      price:2479.99,
      description:'Etekler, Üste oturan kesim, Yüksek bel, Yan cepler, Arkada fermuarlı kapatma, Arkadan yırtmaçlı',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%58 Polyester, %35 Akrilik, %7 Elastan',
      color:'Siyah',
      beden:['XS','S','M','L','XL'],
      stock:11,
    },
    {
      _id:'29',
      image:'/resimler/resim29.jpg',
      image2:'/resimler/mos1.jpg', 
      image3:'/resimler/mos2.jpg',
      image4:'/resimler/mos3.jpg',    
      brand:'MOSCHİNO',
      name:'Kadın Giyim',  
      yorum:459,
      price:2299.99,
      description:'Svetşörtler, Yuvarlak yaka, Uzun kollar, Ribana kenar',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%100 Pamuk',
      color:'Pembe',
      beden:['XS','S','M','L','XL'],
      stock:39,
    },
    {
      _id:'30',
      image:'/resimler/resim30.jpg',
      image2:'/resimler/mos4.jpg', 
      image3:'/resimler/mos5.jpg',
      image4:'/resimler/mos6.jpg',    
      brand:'MOSCHİNO',
      name:'Kadın Giyim',  
      yorum:132,
      price:3749.99,
      description:'Kazaklar, Yuvarlak yaka',
      icerikbir:'Genellikle 2 iş günü içerisinde temin edilir.',
      icerikiki:'%88 Viskoz, %12 Polyester',
      color:'Bej',
      beden:['XS','S','M','L','XL'],
      stock:26,
    }
         
    ]
    } 
    
    export default data