export const TYPES={
    LOGIN:'LOGIN',
    PRODUCT_LIST_REQUEST:'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS:'PRODUCT_LIST_SUCCESS',
    PRODUCT_DETAIL_REQUEST:'PRODUCT_DETAIL_REQUEST',
    PRODUCT_DETAIL_SUCCESS:'PRODUCT_DETAIL_SUCCESS',
    CARD_ADD_ITEM:'CARD_ADD_ITEM', 
    MESSAGE:'MESSAGE',
    CARD_REMOVE_ITEM:'CARD_REMOVE_ITEM',
    SIDE_BAR:'SIDE_BAR',
    FILTER_PRODUCTS_SIZE:'FILTER_PRODUCTS_SIZE',
    ORDER_PRODUCTS_PRICE:'ORDER_PRODUCTS_PRICE',
    ADMIN_ADD_PRODUCT:'ADMIN_ADD_PRODUCT'  
}